# path to render final prometheus config file
target_prometheus_config: example/prometheus.yaml

# define multiple prometheus config sources
# prometheus config with weight=1 will be used as base prometheus config file
prometheus_configs:
  - id: baseconfig
    path: example/prometheus_current.yaml
    weight: 1
  - id: operatorconfig
    path: example/prometheus_operator.yaml
    weight: 2
  - id: fetchfromkubernetes1
    kubernetes:
      secret:
        name: prometheus-squad-a
        key: prometheus.yaml
        namespace: default
    path: example/fetchfromkubernetes_1.yaml
    weight: 3
  - id: fetchfromkubernetes2
    kubernetes:
      configmap:
        name: k8s-prometheus-operator
        key: prometheus.yaml
        namespace: default
    path: example/fetchfromkubernetes_2.yaml
    weight: 4
  # add as many prometheus config as you like. example:
  # - id: anotherconfig
  #   path: example/another_prometheus.yaml
  #   weight: 3

# define where prometheus-server endpoint is
prometheus_endpoint: http://127.0.0.1:9090

# define kubernetes specific configuration
kubernetes:
  incluster: true

server_listen_external: "http://localhost:5000"